version: "3"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.37.0
    ports:
      - "16686:16686"
      - "14250"

  prometheus:
    image: prom/prometheus:v2.38.0
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage  # Required for Chapter 7 - Exemplars
    volumes:
      - /dev/null:/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.64.0
    command:
      - --config=/etc/otel-collector.yml
    volumes:
      - ./otel-collector.yml:/etc/otel-collector.yml
    ports:
      - "4317:4317"
    depends_on:
      - jaeger
      - prometheus
